package Optionals;

import java.util.Optional;

public class OptionalBasicImpl {

    static void optional_ofImpl(){
        // Used when the value is definitely NOT null
        //If you pass null, it throws NullPointerException
        System.out.println("of impl");

        Optional<String> opt1 = Optional.of("ABC");
        System.out.println(opt1.get());
    }

    static void optional_ofNullableImpl(){
        System.out.println("1) of nullbale impl");
        // optionals.ofNullable
        String name = null;
        Optional<String> opt2 = Optional.ofNullable(name);
        // can give opt2.get() can give no such element exception
    }

    static void optional_isPresentImpl(){
        System.out.println("2) is present impl");
        // optionals.isPresent
        Optional<String> opt3 = Optional.of("java");

        // if optional is empty then .get() can give noSuchElement
        if(opt3.isPresent()) System.out.println(opt3.get());
    }
    static void optional_orElseImpl(){
        System.out.println("3) or else impl");
        // optionals.isPresent
        Optional<String> opt3 = Optional.ofNullable(null);
        String username = opt3.orElse("Default value");
        System.out.println(username);
    }

    static void optional_orElseGetImpl(){
        System.out.println("4) or else get impl");
        // similar to orElse but default is generated using lambada function
        Optional<String> opt1 = Optional.ofNullable(null);   // return empty optional only.
        String displayName1 = opt1.orElseGet(()->"Display name 1");
        System.out.println(displayName1);

        Optional<String> opt2 = Optional.empty();
        String displayName2 = opt2.orElseGet(()-> "Display name 2");
        System.out.println(displayName2);
    }

    static void optional_orElseThrowImpl(){
        System.out.println("5) or else throw impl");
        // similar to orElse but default is generated using lambada function
       Optional<String> opt1 = Optional.ofNullable(null);
//       String name1 = opt1.orElseThrow();
        String name1 = opt1.orElseThrow(()-> new RuntimeException("this error is generated by me"));
        System.out.println(name1);
    }


    public static void main(String[] args) {

        // storing values in optional
        optional_ofImpl();
        optional_ofNullableImpl();

        // getting values from optional
        optional_isPresentImpl();    // isPresent and get()

        /*
        Difference with orElse()
         /*
        Method	        Behavior
        orElse()	    returns default value
        orElseGet()	    generates default value
        orElseThrow()	throws exception
        */

        optional_orElseImpl();
        optional_orElseGetImpl();
//      optional_orElseThrowImpl();  default is similar to .get() ,
//      used to throw error (custom  also) if optional is empty.



//      ----------------------------------------------------------
        // no such element exception
        try{
            Optional<String> opt4 = Optional.empty();
            opt4.get();
        }
        catch (Exception e){
            System.out.println(e);
        }
//      ------------------------------------------------------------








    }


}
